import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '@/src/views/style/global.scss'
import { Header } from '@/src/widgets/header/Header'
import { Footer } from '@/src/widgets/footer/Footer'

const geistSans = localFont({
	src: '../src/views/fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900'
})
const geistMono = localFont({
	src: '../src/views/fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div className='min-h-screen flex flex-col'>
					<Header />
					<main className='flex-1'>{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	)
}
